plot_directories: # Directories (folder paths) where your plots are located.
  - ...
  - ...
farmer_secret_key: ... # The secret key extracted from your mnemonic phrase. Please use `extract_farmer_key.py` Python script to extract the Farmer secret key.
launcher_id: ... # Your launcher ID found in `chia plotnft show`, or in the GUI Pool Overview.
worker_name: ...  # Arbitrary worker name. This will show on your Flexpool dashboard. [default: <hostname of the system>]
region: ... # Select the closest region here. Applicable values are `us`, `de`, `sg`, and `cn` (please enter your region without `` quotes).
payout_address: ... # The payout address to use. Both pool and farmer rewards will be pointed to it.

################################
## Other (optional) settings  ##
## (Uncomment them to enable) ##
################################
# prometheus_metrics_listen: localhost:8085 # Prometheus metrics endpoint
# log_file_path: log.txt # Write logs to a specific file
# log_file_level: info # Log level to use when writing logs to file. Initialization logs will ignore this setting. [default: info]
# api_server_listen: localhost:8080 # Start HTTP API server (see API_DOCUMENTATION.txt for docs)
# prometheus_push_gateway:
#   url:  http://localhost:9091 # URL of the remote prometheus push gateway
#   push_interval: 30 # Interval between pushes in seconds [default: 30]
#   username: user # HTTP Basic Auth username
#   password: pass # HTTP Basic Auth password
#   job_name: flexfarmer # Prometheus job name [default: flexfarmer]
#   instance_name: default # Instance name to use [default: "default"]
# max_async_plot_load_threads: # Plot initialization concurrency limit [default: 1024]
# ignore_healthchecks: <true/false> # Ignore failing pool region healthchecks [default: false]
# notifications:
#   - type: discord-webhook
#     discord_webhook: <discord webhook https://-prefixed URL here>
# self_hosted_node_url: wss://localhost:8444/ws # Farm using a self-hosted local (or remote) Chia node
# sequential_plot_load_mode: <true/false> # Disable concurrent plot load (usually done to prevent all drives spinning at once) [default: false]
# sequential_plot_load_delay: 1 # In seconds, specifies the time to wait between switching to initializing another drive. Allowed only if sequential plot load mode is enabled [default: 0]
# disable_direct_io: <true/false> # Disable Direct I/O when farming (this can lead to increased CPU and Memory footprint, and increased lookup times) [default: false]
# gigahorse:
#   disable_hw: <true/false> # Disable hardware acceleration (GPU) for Gigahorse plots. If enabled, FlexFarmer will use CPU only.
#   remote_addr: <host:port> # Specify remote recompute server address to use. You can specify multiple servers separated by comma (,).